plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bommbba.myslitel'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bommbba.myslitel'
        minSdk 26
        targetSdk 33
        versionCode 7
        versionName '0.5'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
